<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>btn_header_top_change_date</name>
   <tag></tag>
   <elementGuidId>f7937cf6-f17b-4ead-8807-2899a914352d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.view.ViewGroup[@content-desc=&quot;touchOpenDateGrafik&quot;])[1]</value>
      <webElementGuid>654d20d9-2826-45b4-93eb-8526fd6d0f42</webElementGuid>
   </webElementProperties>
   <locator>(//android.view.ViewGroup[@content-desc=&quot;touchOpenDateGrafik&quot;])[1]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
