<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>text_field_global_dynamic_duo</name>
   <tag></tag>
   <elementGuidId>d0b7769b-6b9f-4173-8338-c03d57b24596</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//android.widget.TextView[@text='${text}'])[${'index'}]</value>
      <webElementGuid>186cd966-127f-492d-bfdf-8171c005dd46</webElementGuid>
   </webElementProperties>
   <locator>(//android.widget.TextView[@text='${text}'])[${'index'}]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
