<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>btn_nav_profile</name>
   <tag></tag>
   <elementGuidId>2a49de4e-7eac-40d1-acfc-22dad16ea95b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.view.ViewGroup[@content-desc=&quot;btnBottomProfil&quot;]</value>
      <webElementGuid>16ed1e37-272a-408c-b8a6-71b4ba082643</webElementGuid>
   </webElementProperties>
   <locator>//android.view.ViewGroup[@content-desc=&quot;btnBottomProfil&quot;]</locator>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
</MobileElementEntity>
